theme: jekyll-theme-slate
title: COVID Doma
description: A collaborative guide to COVID-19 care
url: https://covid-doma.info
slug: covid-doma
goatcounter: covid-doma

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
